### ISSUE TITLE
Wind Tunnel Scenario - Network performance

### ISSUE THREAD

**Issue by abe-njama** [holochain/wind-tunnel#28]
- [x] Time to receive required validation receipts
- [x] Remote call send/receive rate
- [ ] Remote signals send rate
- [x] #54
- [ ] #55

**Comment by maackle** [comment]
I'm not sure how InfluxDB works and the queries available, but it seems what all of these metrics share in common is that we are performing operations on groups of log events across multiple nodes.

For "Remote signals send rate" and "Remote call send/receive rate", we are just finding the duration which is the difference of instants on two nodes. For remote calls, there are two durations, one for the request and one for the response. We might also want to find averages and percentiles of the aggregate of these durations, also groupable/queryable by node (incoming to one node / outgoing from one node)

"Time to receive required validation receipts" and "Rate of saturation to reach target redundancy with publishing (fast push)" are closely related, since saturation is defined in terms of validation receipts. 

I read the "rate of saturation" to mean the maximum of durations from the moment node A publishes an op to the moment that N other nodes have sent their validation receipts, i.e. the time it takes for N nodes to objectively be holding an op. This may be tricky to write, since the query has to limited to the first N.

I'm not sure how to interpret "time to receive required validation receipts" as a distinct metric. It could be an extension of the previous, where all logging happens on a single node, recording total time from moment of publishing to the moment of receiving N receipts, but this is not a pure network test since it captures the time it takes to do some work on the remote nodes. To make this a more pure test, we could say that this is just about the time it takes the remotes to send back their receipts, though this is a bit ill-defined too, since each remote will be sending back at a different time. TODO: clarify this metric.

Note also that publishing happens in two steps: publishing the op hash, and then being requested the actual op via the recipient's FetchPool. Both durations could be recorded.

"Measure how much time is spent on rebuilding the time tree during gossip at the DHT size grows" is a simple duration measurable on a single node. Note that currently we do not build a time tree, we compute the lookup fresh each time, so this could be a metric of how long it takes the arc lookup to complete. It's not exactly a network performance metric per se, though it is a crucial part of the setup for successful gossip.

TODO: what other metrics? Anything around gossip? Gossip round duration?

**Comment by maackle** [comment]
I'll do another pass of this keeping in mind this is about actually conceiving of full scenarios to write. And we probably want to avoid the need for omniscience

**Comment by maackle** [comment]
won't do: "Rate of saturation to reach target redundancy with publishing (fast push)" cannot be measured from the vantage point of a single node.
won't do: "Measure how much time is spent on rebuilding the time tree during gossip at the DHT size grows" -- we don't maintain a time tree right now so this is not something to measure

### Common Network Initialization (CNI)

This is probably a common procedure for lots of scenarios.

- spin up N nodes with a given DNA installed as a single-cell app
- each node waits until N - 1 peers are visible
- each node establishes that they can send a remote signal to all other nodes, retrying as needed

at this point we know that all N nodes are online and able to communicate

### Time to receive required validation receipts

#### scenario

- do CNI
- one node publishes an op
- when that node receives R receipts, record the duration since publishing as a metric

#### metrics

the duration is the sole metric output of this scenario

### Remote signals send rate

Lots of ways to do this. Here's one:

#### scenario

- do CNI
- each node sends signals as fast as possible to each other node in round-robin fashion and records the timestamp of each send
- each node records the timestamp of receiving a signal from another node
- on scenario end, record the total duration since CNI

#### metrics

two simple metrics can fall out of this:
- avg_send_rate(interval) = total signals sent / total duration since CNI (can also be calculated over smaller time intervals)
- delivery_ratio(time) = # signals received / # signals sent, from CNI to the given time

### Remote call send/receive rate

#### scenario

- do CNI
- each node makes remote calls as fast as possible to each other node in round-robin fashion, recording the timestamp of the send
- each node records the duration between sending the request and receiving the response
- on scenario end, record the total duration since CNI

#### metrics

- avg_call_rate(interval) = total calls made / total duration since CNI (can also be calculated over smaller time intervals)
- avg_roundtrip_time

**Comment by ThetaSinner** [comment]
Most done, new epic for MVP on WT
