### ISSUE TITLE
SPIKE: Minimise differences between build script and Nix build

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/wind-tunnel#97]
Currently it's possible to set up a project that will be accepted and built by the built script but not by Nix. This should be minimized to avoid confusing build errors when going from local development to CI

**Comment by ThetaSinner** [comment]
- Compare a Rust approach to what's been done with Nix. If we can do it cleanly, or comparatively cleanly to the Nix approach then we should do that
- Option to document what the Nix code is doing and how the paths/project names need to be set up
- Maybe make the Nix build give better feedback

**Comment by ThetaSinner** [comment]
Time box to 3 days

**Comment by cdunster** [comment]
@ThetaSinner and @neonphog, I think that you two are the closest to this issue so please read my explored and proposed solutions below and let me know if you have a preference or a new proposal.

1. (Proposed in #122) Fail the cargo build if the scenario directory doesn't match the name.
   - Fails early so the build is caught locally instead of in the CI.
   - Smallest, simplest solution.
   - con: The fix is a manual rename of the directory or package.
   - con: Still requires the zomes and scenarios to be named differently.
2. Just use the cargo package name as the nix package name
   - Avoids the issue where it works with `cargo run` but not `nix run`.
   - con: Can end up in a weird state where the scenarios are in misnamed directories.
   - con: Still requires the zomes and scenarios to be named differently.
3. Create templates and use them to create scenarios and zomes that enforce the naming convention
   - Automates the creation of zomes and scenarios and enforces any rules we put in place.
   - con: Relies on people using the templates manually or via scripts.
   - con: Need to maintain the scripts.
   - con: Do we use Nix or is that the same fundamental issue?
4. Make all the scenarios integration tests in the `test` folder
   - Zomes and scenarios can have the same name and the name of them is taken from the module name so they should never mismatch.
   - Seems to be what tokio does: https://github.com/tokio-rs/tokio/blob/master/tests-integration/Cargo.toml
   - Allows running scenarios with `cargo test --test <scenario_name>`.
   - con: Can't have separate `Cargo.toml`'s per scenario.
   - con: Will need to use something other than `package.metadata` to specify the DNAs etc. (maybe features).
5. Make all the scenarios examples in the `examples` folder
   - Zomes and scenarios can have the same name and the name of them is taken from the module name so they should never mismatch.
   - Allows running scenarios with `cargo run --example <scenario_name>`.
   - con: Can't have separate `Cargo.toml`'s per scenario.
   - con: Will need to use something other than `package.metadata` to specify the DNAs etc. (maybe features).
6. Create a separate cargo workspace just for the scenarios
   - Zomes and scenarios can have the same name as they are in different workspaces.
   - Can keep everything as is with separate `Cargo.toml`'s per scenario and using `package.metadata` for DNAs etc.
   - con: Multiple workspaces per repo is... weird.
   - con: Running is convoluted with `cargo --manifest-file scenarios/Cargo.toml -p <scenario_name>`.
   - Could use `cargo-make` to automate some of this but then that's another dependency and tool for people to learn and use.

**Comment by ThetaSinner** [comment]
I like 1, I think that's a good balance of value for effort.
2. I think the cons make that not a great option
3. I'd like if we did it via the scaffolding. I.e. we have a way of scaffolding WT scenarios into general projects and we consume that within WT itself. I'd prefer not to build a solution that is just for this repo
4./5. I think these make building a binary more complex. The scenarios are supposed to compile into command line tools, although that is hidden in the framework and it's super visible. But I don't want to deal with having the code needing libtest to run on other systems. I think that's what would end up being required there. it might make development simpler but the deploy matters to me too.
6. Along these lines, we might consider splitting the framework code out of the repository. I think it'd be helpful to keep scenario code separate from the framework but I think the scenarios and zomes need to be close together for development speed. I'd be up for an investigation of what this would look like but I do agree that two workspaces is odd.

**Comment by neonphog** [comment]
I guess where I'm at is I don't understand the benefits of nix in this case. We're having to spend a lot of time on it, when I can build and run trycp scenarios just fine outside of it. It's all setup to build the zomes/apps in the [scenario_build.rs](https://github.com/holochain/wind-tunnel/blob/2fc60bdf03d7952a3cd5522db49585c81ab11570/scenarios/scenario_build.rs) and that works perfectly.

I realize nix *wants* you to do everything through it, but that's not a requirement. If we still wanted system-libraries / rust version, etc to be specified by nix, we could do that as a base system, but let cargo handle the rust dependency building and only have to solve that problem once.

**Comment by cdunster** [comment]
@ThetaSinner, okay then I'll continue with #122 as the first step then :+1:.

I like the idea of splitting out the scenarios from the Wind Tunnel framework and using scaffolding. I even think that the scenarios could live in the mono-repo and the mono-repo just becomes a user of Wind Tunnel just like any other hApp.

@neonphog, I think that is how it's set up now, it's just that the CI uses Nix to run the scenarios. This could be changed to be something like `nix develop .#ci -c cargo run scenario` but then we are packaging with Nix right now anyway so we'd still have this problem at that stage. Maybe this is something to discuss in the "Nix or not" meeting tomorrow about whether we should keep using Nix in the CI.
